# Python
---

### Python 구조

In [ ]:
#Python Packages 사용하기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#Keras Packages
import keras
from keras.layers import Input, Dense
from keras.models import Model

In [ ]:
#package 내의 함수사용
np.array()

### Python 기초

In [3]:
#작업공간 찾기와 설정
import os
os.getcwd()

'C:\\Users\\user\\Desktop'

In [ ]:
os.chdir('C:\\Users\\begas\\skkim\\2.code')

In [5]:
os.getcwd()

'C:\\Users\\user\\Desktop'

In [6]:
#숫자형 예시
int(True)

1

In [7]:
int(False)

0

In [8]:
int(99.5)

99

In [9]:
int('88')

88

In [10]:
float(True)

1.0

In [12]:
float(False)

0.0

In [13]:
float(99)

99.0

In [14]:
float('88')

88.0

In [15]:
6+3j

(6+3j)

In [16]:
#논리형 예시
1==1

True

In [17]:
1 < 2

True

In [18]:
1 <= 2

True

In [19]:
bool(1)

True

In [20]:
bool(0)

False

In [22]:
#문자열형 예시
'''triple Quotes'''

'triple Quotes'

In [23]:
print('''triple Quotes''')

triple Quotes


In [24]:
str(98.6)

'98.6'

In [25]:
'a'+'b'

'ab'

In [27]:
'a'*5

'aaaaa'

In [29]:
temp ='abcd'

In [30]:
temp[0], temp[1], temp[2:], temp[:]

('a', 'b', 'cd', 'abcd')

In [31]:
len(temp)

4

In [32]:
print('Triple \n Quotes')

Triple 
 Quotes


In [33]:
temp = '%d %s integer part of %.2f'

In [34]:
temp % (4, 'is', 4.556)

'4 is integer part of 4.56'

In [35]:
temp='abcd!'

In [36]:
temp.startswith('a')    

True

In [37]:
temp.endswith('!')  

True

In [38]:
temp.replace('ab','AB') 

'ABcd!'

In [39]:
'abcd'.upper()  

'ABCD'

In [40]:
'ABCD'.lower()  

'abcd'

In [41]:
'f'.join('abcd')    

'afbfcfd'

In [42]:
#출력하기
print('abcd')

abcd


In [43]:
print('a' 'b' 'c' 'd')

abcd


In [44]:
print('a'+'b'+'c'+'d')

abcd


In [45]:
print('a','b','c','d')

a b c d


In [46]:
print("Accuracy: %.2f" % 0.98)

Accuracy: 0.98


In [47]:
#데이터 연산
1+2

3

In [48]:
1-2

-1

In [49]:
1*2

2

In [50]:
1/2

0.5

In [51]:
1//2

0

In [52]:
1%2

1

In [53]:
2**5

32

In [54]:
4//2*2+1%2

5

In [55]:
1==2

False

In [56]:
1!=2

True

In [57]:
1<2

True

In [58]:
1>2

False

In [59]:
a=[1,2,3]

In [61]:
b=a

In [62]:
c=list(a)

In [63]:
a is b

True

In [64]:
a is c

False

In [65]:
a is not c

True

In [66]:
a=3

In [67]:
b=5

In [68]:
a,b

(3, 5)

In [69]:
a,b=b,a

In [70]:
a,b

(5, 3)

In [71]:
del(a)

In [ ]:
a

### 데이터 구조

In [ ]:
#리스트 데이터 변경
a=[1,2,3,4]

In [ ]:
a[0]=100

In [ ]:
a

In [ ]:
a.append(8)

In [ ]:
a

In [ ]:
a.remove(6)

In [ ]:
a

In [ ]:
a.insert(1,2)

In [ ]:
a

In [ ]:
a.pop(1)

In [ ]:
a

In [ ]:
#리스트 데이터 참조하기
a=[4,6,1,9]

In [ ]:
a[1:3]

In [ ]:
a[:3]

In [ ]:
a[:-2]

In [ ]:
a[:]

In [ ]:
#리스트 데이터 복사
a_copy1=a

In [ ]:
a_copy1

In [ ]:
a_copy2=a[:]

In [ ]:
a_copy2

In [ ]:
a is a_copy1

In [ ]:
a is a_copy2

In [ ]:
#리스트 데이터 합치기 및 확장하기
a=[1,2,3]

In [ ]:
b=[4,5,6]

In [ ]:
c=a+b
c

In [ ]:
a.extend(b)
a

In [ ]:
#리스트 삭제
a=[1,2,3,4]

In [ ]:
del a[0]
a

In [ ]:
del a[1:3]
a

In [ ]:
del a[:]
a

In [ ]:
del a
a

In [ ]:
#튜플
a_tup = 4,5,6
a_tup

In [ ]:
nested_tup = (4,5,6),(7,8)
nested_tup

In [72]:
tup = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [73]:
#Set 연산
set([2,1,3])

{1, 2, 3}

In [74]:
{3,2,1}

{1, 2, 3}

In [76]:
s = set("Hello")
s

{'H', 'e', 'l', 'o'}

In [78]:
a={1,2,3,4}
b={3,4,5,6}
a|b

{1, 2, 3, 4, 5, 6}

In [79]:
a&b

{3, 4}

In [80]:
a-b

{1, 2}

In [81]:
a^b

{1, 2, 5, 6}

In [82]:
#사전형
di = {'a': 'string', 'b':[1,2,3,4]}
di

{'a': 'string', 'b': [1, 2, 3, 4]}

In [83]:
di.keys()

dict_keys(['a', 'b'])

In [84]:
di.values()

dict_values(['string', [1, 2, 3, 4]])

In [85]:
di = dict(a='string', b=[1,2,3,4])
di

{'a': 'string', 'b': [1, 2, 3, 4]}

In [86]:
#데이터 추가, 삭제
di['c']=1
di

{'a': 'string', 'b': [1, 2, 3, 4], 'c': 1}

In [87]:
del di['a']
di

{'b': [1, 2, 3, 4], 'c': 1}

In [89]:
#데이터 변경, 확인
di['b'][1]=5
di

{'b': [1, 5, 3, 4], 'c': 1}

In [90]:
'a' in di

False

In [91]:
'b' in di

True

In [93]:
#Numpy ndarray 다차원 배열 객체
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [94]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
arr2.ndim

2

In [96]:
arr2.shape

(2, 4)

In [97]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [98]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [99]:
np.dot(arr, arr.T)

array([[ 14.,  32.],
       [ 32.,  77.]])

In [100]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [101]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [102]:
arr **0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [103]:
arr_mat = np.mat(arr)
arr_mat*arr_mat.T

matrix([[ 14.,  32.],
        [ 32.,  77.]])

In [105]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr[5]

5

In [107]:
arr[5:8]

array([5, 6, 7])

In [108]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [109]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [110]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
arr3d[0][0]

array([1, 2, 3])

In [113]:
arr3d[0]=1
arr3d

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [114]:
arr3d[0]=np.array([[11,12,13],[14,15,16]])
arr3d

array([[[11, 12, 13],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [118]:
arr2d[1, :2]

array([4, 5])

In [119]:
arr2d[2, :1]

array([7])

In [120]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### 데이터 입/출력

In [ ]:
#텍스트 파일 이용하는 방법
import pandas as pd
df = pd.read_csv("~path/ch06/ex1.csv")
df

In [ ]:
pd.read_table('~path/ch06/ex1.csv', sep=',')

In [ ]:
df.dtypes

In [ ]:
pd.read_csv('~path/ch06/ex2.csv', header=None)

In [ ]:
pd.read_csv('~path/ch06/ex2.csv')

In [ ]:
pd.read_csv('~path/ch06/ex2.csv', names=['a', 'b', 'c', 'd', 'message’])

In [ ]:
names=['a', 'b', 'c', 'd', 'message']
pd.read_csv('~path/ch06/ex2.csv', names=['a','b','c','d','message'], index_col='message')

In [ ]:
pd.read_csv('C:/Users/user/Desktop/pydata-book-master/ch06/csv_mindex.csv')

In [ ]:
pd.read_csv('C:/Users/user/Desktop/pydata-book-master/ch06/csv_mindex.csv',index_col=['key1', 'key2'])

In [ ]:
list(open('~path/ch06/ex3.txt'))

In [ ]:
result = pd.read_table('~path/ch06/ex3.txt', sep='\s+’)
result

In [ ]:
result = pd.read_csv('~path/ch06/ex5.csv', na_values=4)
result

In [ ]:
sentinels = {'message': ['foo', 'NA'], 'something':['two']}
pd.read_csv('~path/ch06/ex5.csv', na_values=sentinels)

In [ ]:
#데이터를 텍스트 형식으로 출력
data = pd.read_csv('~path/ch06/ex5.csv')
data

In [ ]:
data.to_csv('~path/ch06/out.csv')

In [ ]:
pd.read_csv('~path/ch06/out.csv')

In [ ]:
import sys
data.to_csv(sys.stdout, na_rep='NULL')

In [ ]:
data.to_csv(sys.stdout, index=False, cols=['a', 'b', 'c’])

In [ ]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('~path/ch06/tseries.csv')
pd.read_csv('~path/ch06/tseries.csv')

### 데이터 핸들링

In [ ]:
#데이터 합치기
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1

In [ ]:
df2 = DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df2

In [ ]:
pd.merge(df1,df2)

In [ ]:
pd.merge(df1,df2, on='key')

In [ ]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df3

In [ ]:
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
df4

In [ ]:
pd.merge(df3, df4, left_on = 'lkey', right_on = 'rkey')

In [ ]:
pd.merge(df1, df2, how='outer')

In [ ]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
df1

In [ ]:
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})
df2

In [ ]:
pd.merge(df1, df2, on='key', how='left')

In [ ]:
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
left1

In [ ]:
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
right1

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True)

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer') 

In [ ]:
lefth = DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
   'key2': [2000, 2001, 2002, 2001, 2002],
   'data': np.arange(5.)})

In [ ]:
righth = DataFrame(np.arange(12).reshape((6, 2)),
   index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',     
   'Ohio', 'Ohio'],
   [2001, 2000, 2000, 2000, 2001, 2002]],
   columns=['event1', 'event2'])

In [ ]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

In [ ]:
pd.merge(lefth, righth, left_on=['key1', 'key2'],right_index=True, how='outer’)

In [ ]:
left2 = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'],
   columns=['Ohio', 'Nevada'])
left2

In [ ]:
right2 = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
   index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])
right2

In [ ]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

In [ ]:
left2.join(right2, how='outer’)

In [ ]:
arr = np.arange(12).reshape((3, 4)) #array형식
arr

In [ ]:
np.concatenate([arr, arr], axis=1)

In [ ]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

In [ ]:
pd.concat([s1, s2, s3], axis=1)

In [ ]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
   index=['f', 'e', 'd', 'c', 'b', 'a'])
a

In [ ]:
b = Series(np.arange(len(a), dtype=np.float64),
   index=['f', 'e', 'd', 'c', 'b', 'a'])
b

In [ ]:
b[-1] = np.nan

In [ ]:
np.where(pd.isnull(a), b, a)

In [ ]:
#재형성과 피벗
data = DataFrame(np.arange(6).reshape((2, 3)),
   index=pd.Index(['Ohio', 'Colorado'], name='state'),
   columns=pd.Index(['one', 'two', 'three'], name='number'))
data

In [ ]:
result = data.stack()
result

In [ ]:
result.unstack()

In [ ]:
result.unstack(0)

In [ ]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s1

In [ ]:
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
s2

In [ ]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

In [ ]:
data2.unstack()

In [ ]:
data2.unstack().stack()

In [ ]:
data2.unstack().stack(dropna=False)

### 데이터 요약

In [ ]:
import numpy as np
from sklearn import datasets

diabetes = datasets.load_diabetes()
diabetes_X = diabetes.data[:, np.newaxis, 2]

min(diabetes_X)

In [ ]:
np.argmin(diabetes_X)

In [ ]:
sum(diabetes_X)

In [ ]:
np.mean(diabetes_X)

In [ ]:
np.median(diabetes_X)

In [ ]:
np.percentile(diabetes_X,50)

In [ ]:
np.var(diabetes_X)

In [ ]:
np.std(diabetes_X)

In [ ]:
eg_data = np.random.randn(5)
np.sort(eg_data)

### 조건문과 반복문, 함수정의

In [ ]:
x=1
if x>0:
    print('It is positive')

In [ ]:
x=1
if x<0:
    print('It is negative')
elif 0<x<5:
    print('Positive but smaller than 5')
else:
    print('Equal to or lager than 5')

In [ ]:
x=[1,2,3,4]
total=0
for i in range(len(x)):
    total=total+x[i]
total

In [ ]:
i=0
x=256
total=0
while x>0:
    if total>500:
        break
    total=total+x
    i=i+1
    print(i)

In [ ]:
def my_function(x,y,z):
    if z>2:
        return z*(x+y)
    else:
        return z/(x+y)